### ISSUE TITLE
Refactor `status.py` module

### ISSUE THREAD

**Issue by swimmwatch** [pylakey/pydantic_aiohttp#1]
Hi! I suggest to refactor module [status.py](https://github.com/pylakey/pydantic_aiohttp/blob/main/pydantic_aiohttp/status.py) and use standard Python module with HTTP status codes ([`http.HTTPStatus`](https://docs.python.org/3/library/http.html#http.HTTPStatus)).

**Comment by pylakey** [comment]
Sounds good
